import type { AppState } from '../types/domain'

export const STORE_KEY = 'cornerstone-state-v1'

export const seedState: AppState = {
  sites: [
    { id: 1, name: 'Demo Site A', location: 'Example Campus A · Room 101', city: 'Example City A', room: 'Room 101', contact: 'Demo Admin', contactPhone: '010-0000-0001', status: 'online', alertCount: 0 },
    { id: 2, name: 'Demo Site B', location: 'Example Campus B · Room 201', city: 'Example City B', room: 'Room 201', contact: 'Demo Operator', contactPhone: '010-0000-0002', status: 'alert', alertCount: 2 },
    { id: 3, name: 'Demo Lab', location: 'Example Lab · Rack Zone', city: 'Example City C', room: 'Lab Rack Zone', contact: 'Demo Viewer', contactPhone: '010-0000-0003', status: 'offline', alertCount: 0 },
  ],
  circuits: [
    {
      id: 'cir-001',
      name: 'Demo Site A Internet Circuit',
      provider: 'Demo ISP A',
      type: '互联网专线',
      siteId: 1,
      bandwidth: 1000,
      monthlyCost: 18800,
      contractStart: '2025-07-01',
      contractEnd: '2026-06-12',
      circuitNo: 'DEMO-INET-001',
      supportPhone: '010-0000-1001',
      publicIp: '203.0.113.8/29',
      status: '正常',
      note: 'Demo primary internet circuit',
      updatedBy: 'admin',
      updatedAt: '2026-05-18 10:12',
    },
    {
      id: 'cir-002',
      name: 'Demo Site A-B MPLS Circuit',
      provider: 'Demo ISP B',
      type: 'MPLS',
      siteId: 2,
      bandwidth: 500,
      monthlyCost: 22600,
      contractStart: '2025-04-20',
      contractEnd: '2026-05-28',
      circuitNo: 'DEMO-MPLS-002',
      supportPhone: '010-0000-1002',
      publicIp: '',
      status: '正常',
      note: 'Demo private WAN circuit',
      updatedBy: 'ops',
      updatedAt: '2026-05-20 15:34',
    },
    {
      id: 'cir-003',
      name: 'Demo Lab SD-WAN Backup',
      provider: 'Demo ISP C',
      type: 'SD-WAN',
      siteId: 3,
      bandwidth: 200,
      monthlyCost: 5200,
      contractStart: '2024-11-01',
      contractEnd: '2026-11-01',
      circuitNo: 'DEMO-SDWAN-003',
      supportPhone: '010-0000-1003',
      publicIp: '198.51.100.16/28',
      status: '故障',
      note: 'Demo degraded backup link',
      updatedBy: 'ops',
      updatedAt: '2026-05-21 09:06',
    },
  ],
  aggregates: [
    { id: 1, network: '192.0.2.0/24', name: 'Demo management address pool' },
    { id: 2, network: '198.51.100.0/24', name: 'Demo lab address pool' },
  ],
  prefixes: [
    { id: 1, aggregateId: 1, network: '192.0.2.0/26', siteId: 1, vlan: '10', usage: 'Demo office network' },
    { id: 2, aggregateId: 1, network: '192.0.2.64/26', siteId: 1, vlan: '20', usage: 'Demo management network' },
    { id: 3, aggregateId: 1, network: '192.0.2.128/26', siteId: 2, vlan: '30', usage: 'Demo branch network' },
    { id: 4, aggregateId: 2, network: '198.51.100.0/26', siteId: 3, vlan: '120', usage: 'Demo lab network' },
  ],
  ipAddresses: [
    { id: 'ip-001', address: '192.0.2.65', prefixId: 2, deviceId: 1, usage: 'Demo core switch management', owner: 'Demo NetOps', status: '已分配' },
    { id: 'ip-002', address: '192.0.2.66', prefixId: 2, deviceId: 2, usage: 'Demo firewall management', owner: 'Demo SecOps', status: '已分配' },
    { id: 'ip-003', address: '192.0.2.129', prefixId: 3, deviceId: 3, usage: 'Demo branch router management', owner: 'Demo NetOps', status: '已分配' },
    { id: 'ip-004', address: '198.51.100.10', prefixId: 4, deviceId: null, usage: 'Demo reserved lab host', owner: 'Demo Lab', status: '预留' },
  ],
  devices: [
    {
      id: 1,
      name: 'SW-DEMO-CORE-01',
      type: '交换机',
      vendor: 'Cisco',
      model: 'Catalyst 9300',
      sn: 'DEMO-SW-0001',
      siteId: 1,
      location: 'Demo Rack A-U12',
      mgmtIpId: 1,
      status: '在线',
      purchaseDate: '2024-03-12',
      warrantyEnd: '2026-06-18',
      purchaseAmount: 82000,
      owner: 'Demo NetOps',
      note: 'Demo core switch',
    },
    {
      id: 2,
      name: 'FW-DEMO-EDGE-01',
      type: '防火墙',
      vendor: 'Huawei',
      model: 'USG6655E',
      sn: 'DEMO-FW-0001',
      siteId: 1,
      location: 'Demo Rack B-U06',
      mgmtIpId: 2,
      status: '在线',
      purchaseDate: '2023-08-20',
      warrantyEnd: '2026-05-30',
      purchaseAmount: 128000,
      owner: 'Demo SecOps',
      note: 'Demo internet edge firewall',
    },
    {
      id: 3,
      name: 'RT-DEMO-WAN-01',
      type: '路由器',
      vendor: 'H3C',
      model: 'MSR 5660',
      sn: 'DEMO-RT-0001',
      siteId: 2,
      location: 'Demo Rack C-U08',
      mgmtIpId: 3,
      status: '维修',
      purchaseDate: '2022-10-01',
      warrantyEnd: '2026-12-01',
      purchaseAmount: 64000,
      owner: 'Demo NetOps',
      note: 'Demo WAN edge router',
    },
  ],
  credentials: [
    { id: 'cred-001', name: 'SW-DEMO-CORE-01 demo credential', deviceId: 1, protocol: 'SSH', port: 22, username: 'demo-netops', authType: 'password', jumpPort: 22 },
    { id: 'cred-002', name: 'FW-DEMO-EDGE-01 demo credential', deviceId: 2, protocol: 'SSH', port: 22, username: 'demo-secops', authType: 'password', jumpPort: 22 },
    { id: 'cred-003', name: 'RT-DEMO-WAN-01 demo credential', deviceId: 3, protocol: 'Telnet', port: 23, username: 'demo-legacy', authType: 'password', jumpPort: 23 },
  ],
  backups: [
    {
      id: 'bak-001',
      deviceId: 1,
      version: 1,
      createdAt: '2026-05-20 02:00:12',
      trigger: '自动定时',
      operator: 'system',
      status: '成功',
      hasChange: false,
      size: 1186,
      note: 'Demo daily backup',
      content: 'hostname SW-DEMO-CORE-01\ninterface Vlan20\n ip address 192.0.2.65 255.255.255.192\nspanning-tree mode rapid-pvst\nntp server 192.0.2.10\nline vty 0 4\n transport input ssh',
    },
    {
      id: 'bak-002',
      deviceId: 1,
      version: 2,
      createdAt: '2026-05-21 02:00:14',
      trigger: '自动定时',
      operator: 'system',
      status: '成功',
      hasChange: true,
      size: 1224,
      note: 'Demo daily backup',
      content: 'hostname SW-DEMO-CORE-01\ninterface Vlan20\n ip address 192.0.2.65 255.255.255.192\nspanning-tree mode rapid-pvst\nntp server 192.0.2.10\nntp server 192.0.2.11\nline vty 0 4\n transport input ssh',
    },
    {
      id: 'bak-003',
      deviceId: 2,
      version: 1,
      createdAt: '2026-05-21 02:01:03',
      trigger: '自动定时',
      operator: 'system',
      status: '失败',
      hasChange: false,
      size: 0,
      note: 'Demo SSH timeout',
      content: '',
    },
  ],
  users: [
    { id: 'user-001', username: 'admin', email: 'admin@example.com', role: '超级管理员', isActive: true },
    { id: 'user-002', username: 'ops', email: 'ops@example.com', role: 'IT运维工程师', isActive: true },
    { id: 'user-003', username: 'viewer', email: 'viewer@example.com', role: '只读查看者', isActive: true },
  ],
  auditLogs: [
    { id: 'log-001', user: 'ops', action: '更新专线状态', resource: 'Demo Lab SD-WAN Backup', detail: '状态由 正常 改为 故障', createdAt: '2026-05-21 09:06', ipAddress: '192.0.2.200', success: 'true' },
    { id: 'log-002', user: 'system', action: '配置备份', resource: 'FW-DEMO-EDGE-01', detail: '备份失败：SSH 超时', createdAt: '2026-05-21 02:01', ipAddress: '127.0.0.1', success: 'false' },
  ],
  vlanGroups: [
    { id: 1, name: 'Demo Site A VLANs', description: 'Demo Site A VLAN group' },
    { id: 2, name: 'Demo Site B VLANs', description: 'Demo Site B VLAN group' },
    { id: 3, name: 'Demo Lab VLANs', description: 'Demo lab VLAN group' },
  ],
  vlans: [
    { id: 1, vid: 10, name: 'Demo Office', groupId: 1, status: 'active', description: 'Demo office network' },
    { id: 2, vid: 20, name: 'Demo Management', groupId: 1, status: 'active', description: 'Demo network management VLAN' },
    { id: 3, vid: 30, name: 'Demo Server', groupId: 1, status: 'active', description: 'Demo server VLAN' },
    { id: 4, vid: 10, name: 'Demo Branch Office', groupId: 2, status: 'active', description: 'Demo branch office network' },
    { id: 5, vid: 120, name: 'Demo Lab', groupId: 3, status: 'active', description: 'Demo lab network' },
    { id: 6, vid: 999, name: 'Demo DMZ', status: 'reserved', description: 'Demo reserved DMZ VLAN' },
  ],
}
