import type { AppState } from '../types/domain'

export const STORE_KEY = 'cornerstone-state-v1'

export const seedState: AppState = {
  sites: [
    { id: 1, name: '演示站点A', location: '示例园区A · 101机房', city: '示例城市A', room: '101机房', contact: '演示管理员', contactPhone: '010-0000-0001', status: 'online', alertCount: 0 },
    { id: 2, name: '演示站点B', location: '示例园区B · 201机房', city: '示例城市B', room: '201机房', contact: '演示操作员', contactPhone: '010-0000-0002', status: 'alert', alertCount: 2 },
    { id: 3, name: '演示实验室', location: '示例实验室 · 机柜区', city: '示例城市C', room: '实验室机柜区', contact: '演示观察员', contactPhone: '010-0000-0003', status: 'offline', alertCount: 0 },
  ],
  circuits: [
    {
      id: 'cir-001',
      name: '演示站点A互联网专线',
      provider: '演示运营商A',
      type: '互联网专线',
      siteId: 1,
      bandwidth: 1000,
      monthlyCost: 18800,
      contractStart: '2025-07-01',
      contractEnd: '2026-06-12',
      circuitNo: 'DEMO-INET-001',
      supportPhone: '010-0000-1001',
      publicIp: '203.0.113.8/29',
      status: '正常',
      note: '演示主用互联网专线',
      updatedBy: 'admin',
      updatedAt: '2026-05-18 10:12',
    },
    {
      id: 'cir-002',
      name: '演示站点A-B MPLS专线',
      provider: '演示运营商B',
      type: 'MPLS',
      siteId: 2,
      bandwidth: 500,
      monthlyCost: 22600,
      contractStart: '2025-04-20',
      contractEnd: '2026-05-28',
      circuitNo: 'DEMO-MPLS-002',
      supportPhone: '010-0000-1002',
      publicIp: '',
      status: '正常',
      note: '演示私有广域网专线',
      updatedBy: 'ops',
      updatedAt: '2026-05-20 15:34',
    },
    {
      id: 'cir-003',
      name: '演示实验室SD-WAN备份',
      provider: '演示运营商C',
      type: 'SD-WAN',
      siteId: 3,
      bandwidth: 200,
      monthlyCost: 5200,
      contractStart: '2024-11-01',
      contractEnd: '2026-11-01',
      circuitNo: 'DEMO-SDWAN-003',
      supportPhone: '010-0000-1003',
      publicIp: '198.51.100.16/28',
      status: '故障',
      note: '演示降级备份链路',
      updatedBy: 'ops',
      updatedAt: '2026-05-21 09:06',
    },
  ],
  aggregates: [
    { id: 1, network: '192.0.2.0/24', name: '演示管理地址池' },
    { id: 2, network: '198.51.100.0/24', name: '演示实验室地址池' },
  ],
  prefixes: [
    { id: 1, aggregateId: 1, network: '192.0.2.0/26', siteId: 1, vlan: '10', usage: '演示办公网络' },
    { id: 2, aggregateId: 1, network: '192.0.2.64/26', siteId: 1, vlan: '20', usage: '演示管理网络' },
    { id: 3, aggregateId: 1, network: '192.0.2.128/26', siteId: 2, vlan: '30', usage: '演示分支网络' },
    { id: 4, aggregateId: 2, network: '198.51.100.0/26', siteId: 3, vlan: '120', usage: '演示实验室网络' },
  ],
  ipAddresses: [
    { id: 'ip-001', address: '192.0.2.65', prefixId: 2, deviceId: 1, usage: '演示核心交换机管理地址', owner: '演示网络组', status: '已分配' },
    { id: 'ip-002', address: '192.0.2.66', prefixId: 2, deviceId: 2, usage: '演示防火墙管理地址', owner: '演示安全组', status: '已分配' },
    { id: 'ip-003', address: '192.0.2.129', prefixId: 3, deviceId: 3, usage: '演示分支路由器管理地址', owner: '演示网络组', status: '已分配' },
    { id: 'ip-004', address: '198.51.100.10', prefixId: 4, deviceId: null, usage: '演示实验室预留主机', owner: '演示实验室', status: '预留' },
  ],
  devices: [
    {
      id: 1,
      name: 'SW-DEMO-CORE-01',
      type: '交换机',
      vendor: 'Cisco',
      model: 'Catalyst 9300',
      sn: 'DEMO-SW-0001',
      siteId: 1,
      location: '演示机柜A-U12',
      mgmtIpId: 1,
      status: '在线',
      purchaseDate: '2024-03-12',
      warrantyEnd: '2026-06-18',
      purchaseAmount: 82000,
      owner: '演示网络组',
      note: '演示核心交换机',
    },
    {
      id: 2,
      name: 'FW-DEMO-EDGE-01',
      type: '防火墙',
      vendor: 'Huawei',
      model: 'USG6655E',
      sn: 'DEMO-FW-0001',
      siteId: 1,
      location: '演示机柜B-U06',
      mgmtIpId: 2,
      status: '在线',
      purchaseDate: '2023-08-20',
      warrantyEnd: '2026-05-30',
      purchaseAmount: 128000,
      owner: '演示安全组',
      note: '演示互联网边界防火墙',
    },
    {
      id: 3,
      name: 'RT-DEMO-WAN-01',
      type: '路由器',
      vendor: 'H3C',
      model: 'MSR 5660',
      sn: 'DEMO-RT-0001',
      siteId: 2,
      location: '演示机柜C-U08',
      mgmtIpId: 3,
      status: '维修',
      purchaseDate: '2022-10-01',
      warrantyEnd: '2026-12-01',
      purchaseAmount: 64000,
      owner: '演示网络组',
      note: '演示广域网边界路由器',
    },
  ],
  credentials: [
    { id: 'cred-001', name: 'SW-DEMO-CORE-01 演示凭证', deviceId: 1, protocol: 'SSH', port: 22, username: 'demo-netops', authType: 'password', jumpPort: 22 },
    { id: 'cred-002', name: 'FW-DEMO-EDGE-01 演示凭证', deviceId: 2, protocol: 'SSH', port: 22, username: 'demo-secops', authType: 'password', jumpPort: 22 },
    { id: 'cred-003', name: 'RT-DEMO-WAN-01 演示凭证', deviceId: 3, protocol: 'Telnet', port: 23, username: 'demo-legacy', authType: 'password', jumpPort: 23 },
  ],
  backups: [
    {
      id: 'bak-001',
      deviceId: 1,
      version: 1,
      createdAt: '2026-05-20 02:00:12',
      created_at: '2026-05-20 02:00:12',
      trigger: '自动定时',
      operator: 'system',
      status: '成功',
      hasChange: false,
      size: 1186,
      note: '演示每日备份',
      content: 'hostname SW-DEMO-CORE-01\ninterface Vlan20\n ip address 192.0.2.65 255.255.255.192\nspanning-tree mode rapid-pvst\nntp server 192.0.2.10\nline vty 0 4\n transport input ssh',
    },
    {
      id: 'bak-002',
      deviceId: 1,
      version: 2,
      createdAt: '2026-05-21 02:00:14',
      created_at: '2026-05-21 02:00:14',
      trigger: '自动定时',
      operator: 'system',
      status: '成功',
      hasChange: true,
      size: 1224,
      note: '演示每日备份',
      content: 'hostname SW-DEMO-CORE-01\ninterface Vlan20\n ip address 192.0.2.65 255.255.255.192\nspanning-tree mode rapid-pvst\nntp server 192.0.2.10\nntp server 192.0.2.11\nline vty 0 4\n transport input ssh',
    },
  ],
  users: [
    { id: 'user-001', username: 'admin', email: 'admin@example.com', role: 'super_admin', role_display_name: '超级管理员', isActive: true, is_superuser: true, permissions: [], display_name: 'admin', is_sso_user: false },
    { id: 'user-002', username: 'ops', email: 'ops@example.com', role: 'engineer', role_display_name: 'IT运维工程师', isActive: true, is_superuser: false, permissions: [], display_name: 'ops', is_sso_user: false },
    { id: 'user-003', username: 'viewer', email: 'viewer@example.com', role: 'viewer', role_display_name: 'IT负责人', isActive: true, is_superuser: false, permissions: [], display_name: 'viewer', is_sso_user: false },
  ],
  auditLogs: [
    { id: 'log-001', user: 'ops', action: '更新专线状态', resource: '演示实验室SD-WAN备份', detail: '状态由 正常 改为 故障', createdAt: '2026-05-21 09:06', ipAddress: '192.0.2.200', success: 'true' },
    { id: 'log-002', user: 'system', action: '配置备份', resource: 'FW-DEMO-EDGE-01', detail: '备份失败：SSH连接超时', createdAt: '2026-05-21 02:01', ipAddress: '127.0.0.1', success: 'false' },
  ],
  vlanGroups: [
    { id: 1, name: '演示站点A VLAN组', description: '演示站点A的VLAN分组' },
    { id: 2, name: '演示站点B VLAN组', description: '演示站点B的VLAN分组' },
    { id: 3, name: '演示实验室 VLAN组', description: '演示实验室的VLAN分组' },
  ],
  vlans: [
    { id: 1, vid: 10, name: '演示办公网络', groupId: 1, status: 'active', description: '演示办公网络VLAN' },
    { id: 2, vid: 20, name: '演示管理网络', groupId: 1, status: 'active', description: '演示设备管理VLAN' },
    { id: 3, vid: 30, name: '演示服务器网络', groupId: 1, status: 'active', description: '演示服务器VLAN' },
    { id: 4, vid: 10, name: '演示分支办公网络', groupId: 2, status: 'active', description: '演示分支办公网络VLAN' },
    { id: 5, vid: 120, name: '演示实验室网络', groupId: 3, status: 'active', description: '演示实验室网络VLAN' },
    { id: 6, vid: 999, name: '演示DMZ网络', status: 'reserved', description: '演示预留DMZ VLAN' },
  ],
}