"""initial baseline

Revision ID: 7767ffc9a3bb
Revises: 
Create Date: 2026-08-09 10:53:20.394971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7767ffc9a3bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregates_id'), 'aggregates', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('sn', sa.String(length=50), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('mgmt_ip_id', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('u_position', sa.Integer(), nullable=True),
    sa.Column('u_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('warranty_end', sa.DateTime(), nullable=True),
    sa.Column('purchase_amount', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mgmt_ip_id'], ['ip_addresses.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('prefix_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('usage', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_method', sa.String(length=20), nullable=True),
    sa.Column('open_ports', sa.String(length=200), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['prefix_id'], ['prefixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_id'), 'ip_addresses', ['id'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_reports_id'), 'monthly_reports', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='规则描述'),
    sa.Column('device_id', sa.Integer(), nullable=True, comment='设备ID（为空则应用于所有设备）'),
    sa.Column('condition_type', sa.String(length=50), nullable=False, comment='条件类型：latency/packet_loss/status'),
    sa.Column('operator', sa.String(length=10), nullable=False, comment='比较操作符：gt/lt/eq/ne'),
    sa.Column('threshold', sa.Float(), nullable=False, comment='阈值'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='告警级别：info/warning/critical'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('notification_channels', sa.JSON(), nullable=True, comment='通知渠道：email/dingtalk/wechat/webhook'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('has_change', sa.Boolean(), nullable=True),
    sa.Column('change_summary', sa.String(length=200), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_id'), 'backups', ['id'], unique=False)
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('contract_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('circuit_no', sa.String(length=50), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('public_ip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('connected_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connected_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuits_id'), 'circuits', ['id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('enable_password', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=True),
    sa.Column('private_key', sa.String(length=2000), nullable=True),
    sa.Column('jump_host', sa.String(length=50), nullable=True),
    sa.Column('jump_port', sa.Integer(), nullable=True),
    sa.Column('jump_username', sa.String(length=50), nullable=True),
    sa.Column('jump_password', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_credential_name')
    )
    op.create_index(op.f('ix_credentials_id'), 'credentials', ['id'], unique=False)
    op.create_table('device_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('sys_descr', sa.String(length=500), nullable=True),
    sa.Column('sys_name', sa.String(length=100), nullable=True),
    sa.Column('sys_object_id', sa.String(length=100), nullable=True),
    sa.Column('sys_location', sa.String(length=200), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('last_seen_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_full_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_index(op.f('ix_device_fingerprints_id'), 'device_fingerprints', ['id'], unique=False)
    op.create_table('inspection_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('cron_expr', sa.String(length=50), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('ip_range', sa.String(length=50), nullable=True),
    sa.Column('snmp_community', sa.String(length=50), nullable=True),
    sa.Column('snmp_version', sa.String(length=10), nullable=True),
    sa.Column('snmp_timeout', sa.Integer(), nullable=True),
    sa.Column('snmp_retries', sa.Integer(), nullable=True),
    sa.Column('tcp_ports', sa.JSON(), nullable=True),
    sa.Column('tcp_timeout_ms', sa.Integer(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('alert_on_offline', sa.Boolean(), nullable=True),
    sa.Column('alert_on_new_device', sa.Boolean(), nullable=True),
    sa.Column('alert_on_fingerprint_change', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_tasks_id'), 'inspection_tasks', ['id'], unique=False)
    op.create_table('link_monitor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('target_ip', sa.String(length=50), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('packet_loss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_monitor_id'), 'link_monitor', ['id'], unique=False)
    op.create_table('prefixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregate_id', sa.Integer(), nullable=True),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.String(length=20), nullable=True),
    sa.Column('usage', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aggregate_id'], ['aggregates.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prefixes_id'), 'prefixes', ['id'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('row_position', sa.Integer(), nullable=True),
    sa.Column('total_u', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_racks_id'), 'racks', ['id'], unique=False)
    op.create_index(op.f('ix_racks_site_id'), 'racks', ['site_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_sso_user', sa.Boolean(), nullable=True),
    sa.Column('is_ldap_user', sa.Boolean(), nullable=True),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True),
    sa.Column('ldap_username', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vlan_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlan_groups_id'), 'vlan_groups', ['id'], unique=False)
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('target_ip', sa.String(length=50), nullable=True, comment='目标IP'),
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='告警类型'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='告警级别'),
    sa.Column('message', sa.String(length=1000), nullable=False, comment='告警消息'),
    sa.Column('current_value', sa.Float(), nullable=True, comment='当前值'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='阈值'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：active/acknowledged/resolved'),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True, comment='确认人'),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True, comment='确认时间'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='恢复时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_records_id'), 'alert_records', ['id'], unique=False)
    op.create_table('backup_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_detail', sa.String(length=500), nullable=True),
    sa.Column('total_added', sa.Integer(), nullable=True),
    sa.Column('total_removed', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_id')
    )
    op.create_index(op.f('ix_backup_analyses_id'), 'backup_analyses', ['id'], unique=False)
    op.create_table('backup_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('cron_expr', sa.String(length=50), nullable=True),
    sa.Column('device_ids', sa.String(length=500), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('retention_count', sa.Integer(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('notify_on_change', sa.Boolean(), nullable=True),
    sa.Column('notify_on_fail', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_backup_task_name')
    )
    op.create_index(op.f('ix_backup_tasks_id'), 'backup_tasks', ['id'], unique=False)
    op.create_table('circuit_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_changes_id'), 'circuit_changes', ['id'], unique=False)
    op.create_table('circuit_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('symptom', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('affected_sites', sa.JSON(), nullable=True),
    sa.Column('reported_by', sa.String(length=50), nullable=True),
    sa.Column('ticket_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_incidents_id'), 'circuit_incidents', ['id'], unique=False)
    op.create_table('device_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=True),
    sa.Column('source_interface', sa.String(length=100), nullable=True),
    sa.Column('target_device_id', sa.Integer(), nullable=True),
    sa.Column('target_interface', sa.String(length=100), nullable=True),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_circuit_id', sa.Integer(), nullable=True),
    sa.Column('target_circuit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['target_circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_links_id'), 'device_links', ['id'], unique=False)
    op.create_table('inspection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_targets', sa.Integer(), nullable=True),
    sa.Column('online_count', sa.Integer(), nullable=True),
    sa.Column('offline_count', sa.Integer(), nullable=True),
    sa.Column('new_device_count', sa.Integer(), nullable=True),
    sa.Column('change_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['inspection_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_results_id'), 'inspection_results', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['vlan_groups.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vlans_id'), 'vlans', ['id'], unique=False)
    op.create_table('alert_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='通知渠道'),
    sa.Column('target', sa.String(length=200), nullable=True, comment='通知目标'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态：pending/sent/failed'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='错误信息'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['alert_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notifications_id'), 'alert_notifications', ['id'], unique=False)
    op.create_table('circuit_incident_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['circuit_incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_incident_logs_id'), 'circuit_incident_logs', ['id'], unique=False)
    op.create_table('inspection_device_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('detection_method', sa.String(length=20), nullable=True),
    sa.Column('open_ports', sa.JSON(), nullable=True),
    sa.Column('sys_descr', sa.String(length=500), nullable=True),
    sa.Column('sys_name', sa.String(length=100), nullable=True),
    sa.Column('sys_object_id', sa.String(length=100), nullable=True),
    sa.Column('sys_up_time', sa.Integer(), nullable=True),
    sa.Column('sys_location', sa.String(length=200), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('is_new_device', sa.Boolean(), nullable=True),
    sa.Column('has_fingerprint_change', sa.Boolean(), nullable=True),
    sa.Column('change_detail', sa.JSON(), nullable=True),
    sa.Column('scan_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['inspection_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_device_results_id'), 'inspection_device_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_device_results_id'), table_name='inspection_device_results')
    op.drop_table('inspection_device_results')
    op.drop_index(op.f('ix_circuit_incident_logs_id'), table_name='circuit_incident_logs')
    op.drop_table('circuit_incident_logs')
    op.drop_index(op.f('ix_alert_notifications_id'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    op.drop_index(op.f('ix_vlans_id'), table_name='vlans')
    op.drop_table('vlans')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_inspection_results_id'), table_name='inspection_results')
    op.drop_table('inspection_results')
    op.drop_index(op.f('ix_device_links_id'), table_name='device_links')
    op.drop_table('device_links')
    op.drop_index(op.f('ix_circuit_incidents_id'), table_name='circuit_incidents')
    op.drop_table('circuit_incidents')
    op.drop_index(op.f('ix_circuit_changes_id'), table_name='circuit_changes')
    op.drop_table('circuit_changes')
    op.drop_index(op.f('ix_backup_tasks_id'), table_name='backup_tasks')
    op.drop_table('backup_tasks')
    op.drop_index(op.f('ix_backup_analyses_id'), table_name='backup_analyses')
    op.drop_table('backup_analyses')
    op.drop_index(op.f('ix_alert_records_id'), table_name='alert_records')
    op.drop_table('alert_records')
    op.drop_index(op.f('ix_vlan_groups_id'), table_name='vlan_groups')
    op.drop_table('vlan_groups')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_racks_site_id'), table_name='racks')
    op.drop_index(op.f('ix_racks_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_prefixes_id'), table_name='prefixes')
    op.drop_table('prefixes')
    op.drop_index(op.f('ix_link_monitor_id'), table_name='link_monitor')
    op.drop_table('link_monitor')
    op.drop_index(op.f('ix_inspection_tasks_id'), table_name='inspection_tasks')
    op.drop_table('inspection_tasks')
    op.drop_index(op.f('ix_device_fingerprints_id'), table_name='device_fingerprints')
    op.drop_table('device_fingerprints')
    op.drop_index(op.f('ix_credentials_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_circuits_id'), table_name='circuits')
    op.drop_table('circuits')
    op.drop_index(op.f('ix_backups_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_monthly_reports_id'), table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index(op.f('ix_ip_addresses_id'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_aggregates_id'), table_name='aggregates')
    op.drop_table('aggregates')
    # ### end Alembic commands ###
